  # version: "3.9"

services:
  jollof-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: jollofai_backend_prod
    ports:
      - "5000:5000"
    env_file: .env
    command: npm start
    profiles: ["prod"]

  jollof-backend-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: jollofai_backend_dev
    ports:
      - "5001:5000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles: ["dev"]
